# Generated by Django 4.0.1 on 2022-05-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=30)),
                ('mensagem', models.TextField(max_length=300)),
                ('dia', models.CharField(max_length=2)),
                ('responsavel', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
