# Generated by Django 4.0.1 on 2022-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mensagem',
            field=models.TextField(max_length=2000),
        ),
    ]
