# Generated by Django 4.0.1 on 2022-05-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='setor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fiscal'), (2, 'Contábil')], default=2),
        ),
    ]
