# Generated by Django 4.0.1 on 2022-06-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmltoexcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pasta',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
