# Generated by Django 4.0.1 on 2022-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmltoexcel', '0002_file_pasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='pasta',
        ),
    ]
