# Generated by Django 4.0.1 on 2023-01-12 16:42

from django.db import migrations, models
import importador.models


class Migration(migrations.Migration):

    dependencies = [
        ('importador', '0002_remove_empresa_status_empresa_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to=importador.models.localsalvar)),
            ],
        ),
    ]
